## Provides autodetected defaults, for vanilla Docker environments,
## please see datadog.yaml.example for all supported options

apm_config:
  apm_non_local_traffic: true

# Use java container support
jmx_use_container_support: true

# allow configuration-provided hostname starting with ip- or domu
hostname_force_config_as_canonical: true

# Use hostname from file
#hostname_file: /var/lib/cloud/data/previous-hostname