name: Stage. Switch Environment (Blue/Green)
run-name: Switch to ${{ inputs.deployment-type }} Environment by ${{ github.actor }} 🚀
on:
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Switch Environment'
        required: true
        type: choice
        options:
          - blue
          - green
          - red
          - white
env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2
  ELB_LISTENER_ARN: arn:aws:elasticloadbalancing:eu-west-2:055854167589:listener/app/sas-app-lb-stage/0273c5bf0d01ab52/ee46bf03270bb022
  BLUE_TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:eu-west-2:055854167589:targetgroup/sas-app-blue-tg-stage/501ac1b353f29215
  GREEN_TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:eu-west-2:055854167589:targetgroup/sas-app-green-tg-stage/eb116f20925cccc0
  RED_TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:eu-west-2:055854167589:targetgroup/sas-app-red-tg-stage/eb116f20925cccc0
  WHITE_TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:eu-west-2:055854167589:targetgroup/sas-app-white-tg-stage/eb116f20925cccc0

jobs:
  switch:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get Default Action Target Group
        id: get-current
        run: |
           CURRENT_TG=$(aws elbv2 describe-listeners \
             --listener-arns "${{ env.ELB_LISTENER_ARN }}" \
             --query "Listeners[0].DefaultActions[0].TargetGroupArn" \
             --output text)

            echo "current_tg=$CURRENT_TG" >> "$GITHUB_OUTPUT"

      - name: Switch Status tag to a new Blue environment
        run: |
            aws elbv2 remove-tags --resource-arns ${{ steps.get-current.outputs.current_tg }} --tag-keys Status
            aws elbv2 add-tags --resource-arns ${{ env.BLUE_TARGET_GROUP_ARN }} --tags Key=Status,Value=Live
        if: ( github.event.inputs.deployment-type == 'blue' )

      - name: Switch Status tag to a new Green environment
        run: |
            aws elbv2 remove-tags --resource-arns ${{ steps.get-current.outputs.current_tg }} --tag-keys Status
            aws elbv2 add-tags --resource-arns ${{ env.GREEN_TARGET_GROUP_ARN }} --tags Key=Status,Value=Live
        if: ( github.event.inputs.deployment-type == 'green' )

      - name: Switch Status tag to a new Red environment
        run: |
            aws elbv2 remove-tags --resource-arns ${{ steps.get-current.outputs.current_tg }} --tag-keys Status
            aws elbv2 add-tags --resource-arns ${{ env.RED_TARGET_GROUP_ARN }} --tags Key=Status,Value=Live
        if: ( github.event.inputs.deployment-type == 'red' )

      - name: Switch Status tag to a new White environment
        run: |
            aws elbv2 remove-tags --resource-arns ${{ steps.get-current.outputs.current_tg }} --tag-keys Status
            aws elbv2 add-tags --resource-arns ${{ env.WHITE_TARGET_GROUP_ARN }} --tags Key=Status,Value=Live
        if: ( github.event.inputs.deployment-type == 'white' )
