name: Stage. Build symfony
on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag name (e.g. 1.500.0)'
        required: true
        type: string
      tag_message:
        description: 'Message for the tag'
        required: true
        type: string

permissions:
  contents: write

env:
    GIT_BRANCH: dev
    TAG_NAME: "${{ github.event.inputs.tag }}"
    TAG_MESSAGE: "${{ github.event.inputs.tag_message }}"
    

jobs:
  create-release-tag:
    name: 'Setup release tag'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout SAS repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ env.GIT_BRANCH }}
      - name: show files
        run: ls -la
      - name: show tag
        run: echo " 💡 Tag $TAG_NAME already exists in git history"
            
            

