name: Production. Enable Maintenance Mode
run-name: Setup Maintenance Page by ${{ github.actor }} 🔥

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Enable or disable maintenance mode"
        required: true
        type: choice
        options:
          - enable
          - disable

      page_type:
        description: "Select maintenance page type (only required when enabling)"
        required: true
        type: choice
        options:
          - provider-issue
          - maintenance-page

env:
  AWS_REGION: eu-west-2
  LISTENER_ARN: ${{ secrets.LISTENER_ARN }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  SSM_PARAM: "/alb/previous-target-group"

permissions:
  id-token: write
  contents: read

jobs:
  maintenance_mode:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Detect current Target Group
        if: ${{ github.event.inputs.action == 'enable' }}
        run: |
          CURRENT_TG=$(aws elbv2 describe-listeners \
            --listener-arn "$LISTENER_ARN" \
            --query "Listeners[0].DefaultActions[0].TargetGroupArn" \
            --output text)

          if [[ "$CURRENT_TG" == "None" || -z "$CURRENT_TG" ]]; then
            echo "❌ No active Target Group found (maybe already in maintenance)"
            exit 1
          fi

          echo "Detected TG: $CURRENT_TG"

          # Save to SSM
          aws ssm put-parameter \
            --name "$SSM_PARAM" \
            --value "$CURRENT_TG" \
            --type String \
            --overwrite

          echo "Saved previous TG to SSM"

      - name: Enable maintenance
        if: ${{ github.event.inputs.action == 'enable' }}
        run: |
         set -e

          if [[ "${{ github.event.inputs.page_type }}" == "provider-issue" ]]; then
            echo "Using provider issue page..."

            HTML='<html><head><title>System Status</title></head><body style="margin:0;background:#ebf4f7;color:#333;font:16px/1.5 Arial,sans-serif"><div style="max-width:560px;margin:64px auto;padding:32px;background:#fff;border:1px solid #ddd;border-top:6px solid #ad2925;border-radius:12px;box-shadow:0 8px 24px rgba(40,96,144,.08);text-align:center"><h2 style="margin:0 0 16px;color:#ad2925">SAS is temporarily unavailable</h2><p style="margin:0 0 12px">We're temporarily offline. One of our service providers is currently experiencing technical difficulties, which is affecting SAS.</p><p style="margin:0 0 12px">We are monitoring the situation closely and will be back online as soon as they resolve the issue.</p><p style="margin:0;color:#ad2925"><b>Thanks for your patience!</b></p></div></body></html>'
          elif [[ "${{ github.event.inputs.page_type }}" == "maintenance-page" ]]; then
            echo "Using scheduled maintenance page..."

            HTML='<html><head><title>Service Maintenance</title></head><body style="margin:0;background:#ebf4f7;color:#333;font:16px/1.5 Arial,sans-serif"><div style="max-width:560px;margin:64px auto;padding:32px;background:#fff;border:1px solid #ddd;border-top:6px solid #ad2925;border-radius:12px;box-shadow:0 8px 24px rgba(40,96,144,.08);text-align:center"><h2 style="margin:0 0 16px;color:#ad2925">Scheduled Maintenance</h2><p style="margin:0 0 12px">Sorry for the inconvenience! We’re currently undergoing scheduled maintenance to improve your experience.</p><p style="margin:0 0 20px">We’ll be back online shortly.</p><p style="margin:0 0 28px;color:#ad2925"><b>Thank you for your patience!</b></p><p style="margin:0;text-align:right">Sincerely,<br>SellerAmp SAS Team</p></div></body></html>'

          else
            echo "Invalid page_type"
          exit 1
          fi

          aws elbv2 modify-listener \
          --listener-arn "$LISTENER_ARN" \
          --default-actions "Type=fixed-response,FixedResponseConfig={StatusCode=503,ContentType=text/html,MessageBody='$HTML'}"

          echo "✅ Maintenance ENABLED with ${{ github.event.inputs.page_type }} page"

      - name: Disable maintenance
        if: ${{ github.event.inputs.action == 'disable' }}
        run: |
          echo "Restoring previous Target Group..."

          PREVIOUS_TG=$(aws ssm get-parameter \
            --name "$SSM_PARAM" \
            --query "Parameter.Value" \
            --output text)

          if [[ -z "$PREVIOUS_TG" || "$PREVIOUS_TG" == "None" ]]; then
            echo "❌ Failed to retrieve previous TG from SSM"
            exit 1
          fi

          echo "Restoring to: $PREVIOUS_TG"

          aws elbv2 modify-listener \
            --listener-arn "$LISTENER_ARN" \
            --default-actions "Type=forward,TargetGroupArn=$PREVIOUS_TG"

          echo "✅ Maintenance DISABLED"
