name: Stage. Run jobs parallel 
run-name: Deploy stage by ${{ github.actor }} 🚀

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g. 1.490.0)'
        required: true
        type: string
      tag_message:
        description: 'Message for the tag'
        required: true
        type: string

permissions:
  contents: write

env:

    GIT_BRANCH: dev
    ENV_FILE: ${{ secrets.SANDBOX_ENV_FILE }}
    TAG_NAME: "${{ github.event.inputs.tag }}"
    TAG_MESSAGE: "${{ github.event.inputs.tag_message }}"
    

jobs:


  build_symfony:
    if: github.event.inputs.tag != ''
    uses: Eugentk/docker/.github/workflows/deploy_symfony.yml@dev
    with:
        tag: github.event.inputs.tag
        tag_message: github.event.inputs.tag_message
    secrets: inherit

  build_yii:
    name: 'Setup release tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SAS repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ env.GIT_BRANCH }}

      - name: Copy .env file
        run: |
            cat >.env <<EOL
            ${{ env.ENV_FILE }}
            EOL
        shell: bash

      - name: set blue deployment .env variable
        run: sed -i~ '/^BLUE_GREEN_ENV=/s/=.*/="blue"/' .env
            