name: Production. Setup Release Tag
run-name: Setup release tag by ${{ github.actor }} 🚀

on:
  workflow_call:
    inputs:
      Tag:
        description: 'Tag name (e.g. 1.490.0)'
        required: true
        type: string
      Tag_message:
        description: 'Message for the tag'
        required: true
        type: string

permissions:
  contents: write

env:
    AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: eu-west-2
    GIT_BRANCH: main
    TAG_NAME: "${{ github.event.inputs.Tag }}"
    TAG_MESSAGE: "${{ github.event.inputs.Tag_message }}"
    SYMFONY_GIT_REPOSITORY_URL: "Eugentk/webhook_jenkins.git"
    SYMFONY_GIT_DEPLOY_KEY_SECRET_NAME: ${{ secrets.SYMFONY_GIT_DEPLOY_KEY }}
    REACT_GIT_REPOSITORY_URL: "git@github.com:Eugentk/Actions.git"
    REACT_GIT_DEPLOY_KEY_SECRET_NAME: ${{ secrets.REACT_GIT_DEPLOY_KEY }}

jobs:
  create-release-tag:
    name: 'Setup release tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SAS repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ env.GIT_BRANCH }}

      - name: Configure SAS Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag for SAS repository
        run: |
          if git tag --list | grep -q "^${TAG_NAME}$"; then
            echo " 💡 Tag $TAG_NAME already exists in git history"
            exit 1
          else
            git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
            git push origin "$TAG_NAME"
          fi

      - name: Copy Symfony git deploy key
        run: |
          touch /tmp/symfony-git-deploy-key.pem
          echo "${{ env.SYMFONY_GIT_DEPLOY_KEY_SECRET_NAME }}" > /tmp/symfony-git-deploy-key.pem
          chmod 0600 /tmp/symfony-git-deploy-key.pem
          mkdir -p /tmp/symfony
        shell: bash

      - name: Clone Symfony repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.SYMFONY_GIT_REPOSITORY_URL }}
          ssh-key: ${{ secrets.SYMFONY_GIT_DEPLOY_KEY }}
          ssh-known-hosts: github.com
          fetch-depth: 0
          ref: ${{ env.GIT_BRANCH }}
          path: symfony

      - name: Configure SAS-Symfony Git user
        run: |
          cd /tmp/symfony
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag for SAS-Symfony repository
        run: |
          cd /tmp/symfony
          if git tag --list | grep -q "^${TAG_NAME}$"; then
            echo " 💡 Tag $TAG_NAME already exists in git history"
            exit 1
          else
            git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
            GIT_SSH_COMMAND="ssh -i /tmp/symfony-git-deploy-key.pem -o StrictHostKeyChecking=no" git push origin ${{ env.TAG_NAME }}
          fi

      - name: Remove Symfony git deploy key
        run: rm /tmp/symfony-git-deploy-key.pem

      - name: Copy react git deploy key
        run: |
          touch /tmp/react-git-deploy-key.pem
          echo "${{ env. REACT_GIT_DEPLOY_KEY_SECRET_NAME }}" > /tmp/react-git-deploy-key.pem
          chmod 0600 /tmp/react-git-deploy-key.pem
          mkdir -p /tmp/react
        shell: bash

      - name: Clone react repository
        run: |
          GIT_SSH_COMMAND="ssh -i /tmp/react-git-deploy-key.pem -o StrictHostKeyChecking=no" git clone --depth 1 --branch ${{ env.GIT_BRANCH }} ${{ env.REACT_GIT_REPOSITORY_URL }} /tmp/react

      - name: Configure SAS-React Git user
        run: |
          cd /tmp/react
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag for SAS-React repository
        run: |
          cd /tmp/react &&
          GET_TAGS="ssh -i /tmp/react-git-deploy-key.pem -o StrictHostKeyChecking=no" git fetch --tags ${{ env.REACT_GIT_REPOSITORY_URL }}
          if git tag --list | grep -q "^${TAG_NAME}$"; then
            echo " 💡 Tag $TAG_NAME already exists in git history"
            exit 1
          else
            git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
            GIT_SSH_COMMAND="ssh -i /tmp/react-git-deploy-key.pem -o StrictHostKeyChecking=no" git push origin ${{ env.TAG_NAME }}
          fi

      - name: Remove react git deploy key
        run: rm /tmp/react-git-deploy-key.pem