name: Setup Release Tag
run-name: Setup release tag by ${{ github.actor }} 🚀

on:
  workflow_dispatch:
    inputs:
      Tag:
        description: 'Tag name (e.g. 1.490.0)'
        required: true
        type: string
      Tag_message:
        description: 'Message for the tag'
        required: true
        type: string

permissions:
  contents: write

env:
    GIT_BRANCH: main
    TAG_NAME: "${{ github.event.inputs.Tag }}"
    TAG_MESSAGE: "${{ github.event.inputs.Tag_message }}"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GIT_BRANCH }}
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag for SAS repository
        run: |
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "❌ Tag $TAG_NAME already exists"
            exit 1
          fi
          git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
          git push origin "$TAG_NAME"