# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
run-name: Build release packages from ${{ github.ref_name }} by ${{ github.actor }} ✅

on:
  push:
    branches:
      - main
jobs:
  job-deploy-java_proto:
    runs-on: self-hosted
    steps:
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: jaegertracing/protobuf:latest
          options: --rm -v ${{ github.workspace }}:/proto -w /proto
          run: |
            protoc --proto_path=proto/messages/ --java_out=./proto/out/java/src/main/java $(find . -iname "*.proto") --experimental_allow_proto3_optional

      - name: Publish package
        run: |
          cd ./proto/out/java
          ./mvnw deploy
#      - name: Send notification to Google Chat
#        run: |
#          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}' \
#          --header 'Content-Type: application/json' \
#          --data-raw '{
#              "cards": [
#                  {
#                      "header": {
#                          "title": "Issue Tracker",
#                          "subtitle": "Issue No: #${{ github.event.issue.number }}"
#                      },
#                      "sections": [
#                          {
#                              "widgets": [
#                                  {
#                                     "keyValue": {
#                                          "topLabel": "Creator",
#                                          "content": "${{ github.event.issue.user.login }}"
#                                      },
#                                   },
#                                   {
#                                     "keyValue": {
#                                          "topLabel": "Title",
#                                          "content": "${{ github.event.issue.title }}"
#                                      }
#                                   },
#                                   {
#                                     "keyValue": {
#                                          "topLabel": "Assigned Lables",
#                                          "content": "- ${{ join(github.event.issue.labels.*.name) }}"
#                                      }
#                                   },
#                                   {
#                                     "keyValue": {
#                                          "topLabel": "Assignees",
#                                          "content": "- ${{ join(github.event.issue.assignees.*.login) }}"
#                                      }
#                                   },
#                                   {
#                                      "buttons": [
#                                          {
#                                              "textButton": {
#                                                  "text": "OPEN ISSUE",
#                                                  "onClick": {
#                                                      "openLink": {
#                                                          "url": "${{ github.event.issue.html_url }}"
#                                                      }
#                                                  }
#                                              }
#                                          }
#                                      ]
#                                  }
#                              ]
#                          }
#                      ]
#                  }
#              ]
#          }'

  job-deploy-php_proto:
    runs-on: self-hosted
    steps:
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get short SHA with Git
        id: sha_git
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Extract version from pom.xml
        id: pom_version
        run: |
          RAW_VERSION=$(grep -m1 "<version>" pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          VERSION=${RAW_VERSION%-SNAPSHOT}
          NEW_TAG="v$VERSION"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: jaegertracing/protobuf:latest
          options: --rm -v ${{ github.workspace }}:/proto -w /proto
          run: | 
            protoc --proto_path=proto/messages/ --php_out=./proto/out/php $(find . -iname "*.proto") --experimental_allow_proto3_optional

      - name: Setup release version and check tag
        id: version
        run: |
          cd ./proto/out/
          
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clone the target repository
          git clone git@github.com:SmartTAB/php-proto-entertainer.git target_repo_name
          
          pwd
          
          rm -rf target_repo_name/*

          # Copy generated files to the target repository
          cp -rf ./php/* target_repo_name/
          
          # Get and increment the latest tag
          cd target_repo_name
          git fetch --tags

          # Read version from pom.xml file
          NEW_TAG="${{ steps.pom_version.outputs.new_tag }}"

          # Prevent duplicate tag
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
             echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Release a new version
        if: steps.version.outputs.tag_exists == 'false'
        run: |
          git add .
          git commit -m "Update PHP proto files - ${{ steps.pom_version.outputs.new_tag }}, entertainer commit: ${{ steps.sha_git.outputs.short_sha }}"
          git tag -a "${{ steps.pom_version.outputs.new_tag }}" -m "Release ${{ steps.pom_version.outputs.new_tag }}"
          git push origin develop
          git push origin "${{ steps.pom_version.outputs.new_tag }}"

      - name: Tag already exists
        if: steps.version.outputs.tag_exists == 'true'
        run: echo "Tag ${{ steps.pom_version.outputs.new_tag }} already exists — skipping release"

#      - name: Send notification to Google Chat
#        run: |
#          curl -X POST -H 'Content-Type: application/json' \
#          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}" \
#          -d @- << EOF
#          {
#            "cardsV2": [
#              {
#                "cardId": "new-release-card",
#                "card": {
#                  "header": {
#                    "title": "🎉 New releace entertainer php proto library publiched",
#                    "subtitle": "https://github.com/SmartTAB/php-proto-entertainer",
#                    "imageUrl": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
#                  },
#                  "sections": [
#                    {
#                      "widgets": [
#                        {
#                          "decoratedText": {
#                            "topLabel": "Version (Tag)",
#                            "text": "<b>${{ steps.sha_git.outputs.new_tag }}</b>"
#                          }
#                        },
#                        {
#                          "decoratedText": {
#                            "topLabel": "Author",
#                            "text": "${{ github.event.release.author.login }}"
#                          }
#                        }
#                      ]
#                    },
#                    {
#                      "widgets": [
#                        {
#                          "buttonList": {
#                            "buttons": [
#                              {
#                                "text": "View release on GitHub",
#                                "onClick": {
#                                  "openLink": {
#                                    "url": "${{ github.event.release.html_url }}"
#                                  }
#                                }
#                              }
#                            ]
#                          }
#                        }
#                      ]
#                    }
#                  ]
#                }
#              }
#            ]
#          }
#          EOF

  job-deploy-js_proto:
    runs-on: self-hosted
    steps:
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract version from pom.xml
        id: pom_version
        run: |
          RAW_VERSION=$(grep -m1 "<version>" pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          VERSION=${RAW_VERSION%-SNAPSHOT}
          NEW_TAG="v$VERSION"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: jaegertracing/protobuf:latest
          options: --rm -v ${{ github.workspace }}:/proto -w /proto
          run: |
            protoc --proto_path=proto/messages/ --js_out=import_style=commonjs,binary:./proto/out/js/proto $(find . -iname "*.proto") --experimental_allow_proto3_optional

      - name: Setup release version and check tag
        id: versionjs
        run: |
          cd ./proto/out/
          
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clone the target repository
          git clone git@github.com:SmartTAB/js-proto-entertainer.git target_repo_name
          
          pwd

          # Copy generated files to the target repository
          cp -rf ./js/* target_repo_name/
          
          # Get and increment the latest tag
          cd target_repo_name
          git fetch --tags

          # Read version from pom.xml file
          NEW_TAG="${{ steps.pom_version.outputs.new_tag }}"

          # Prevent duplicate tag
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
             echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Release a new js version
        if: steps.versionjs.outputs.tag_exists == 'false'
        run: |
          git add .
          git commit -m "Update JS proto files - ${{ steps.pom_version.outputs.new_tag }}"
          git tag -a "${{ steps.pom_version.outputs.new_tag }}" -m "Release ${{ steps.pom_version.outputs.new_tag }}"
          git push origin develop
          git push origin "${{ steps.pom_version.outputs.new_tag }}"

      - name: Tag already exists
        if: steps.versionjs.outputs.tag_exists == 'true'
        run: echo "Tag ${{ steps.pom_version.outputs.new_tag }} already exists — skipping release"


  job-package_component:
    needs: job-deploy-java_proto
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          overwrite-settings: false
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build with Maven
        run: ./mvnw deploy
#      - name: Send notification to Google Chat
#        run: |
#          curl -X POST -H 'Content-Type: application/json' \
#          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}" \
#          -d @- << EOF
#          {
#            "cardsV2": [
#              {
#                "cardId": "new-release-card",
#                "card": {
#                  "header": {
#                    "title": "🎉 New releace entertainer library publiched",
#                    "subtitle": "${{ github.repository }}",
#                    "imageUrl": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
#                  },
#                  "sections": [
#                    {
#                      "widgets": [
#                        {
#                          "decoratedText": {
#                            "topLabel": "Version (Tag)",
#                            "text": "<b>${{ github.event.release.tag_name }}</b>"
#                          }
#                        },
#                        {
#                          "decoratedText": {
#                            "topLabel": "Author",
#                            "text": "${{ github.event.release.author.login }}"
#                          }
#                        }
#                      ]
#                    },
#                    {
#                      "widgets": [
#                        {
#                          "buttonList": {
#                            "buttons": [
#                              {
#                                "text": "View release on GitHub",
#                                "onClick": {
#                                  "openLink": {
#                                    "url": "${{ github.event.release.html_url }}"
#                                  }
#                                }
#                              }
#                            ]
#                          }
#                        }
#                      ]
#                    }
#                  ]
#                }
#              }
#            ]
#          }
#          EOF