name: Production. Setup Release version
run-name: Setup release to ${{ github.ref_name }} by ${{ github.actor }} ✅

on:
  workflow_dispatch:
   

permissions:
  contents: write
  actions: write

env:

  GIT_BRANCH: main

  SYMFONY_GIT_REPOSITORY_URL: git@github.com:Eugentk/Actions.git
  SYMFONY_GIT_DEPLOY_KEY: ${{ secrets.SYMFONY_GIT_DEPLOY_KEY }}

jobs:
  move-stable-tag:
    name: Move stable tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SAS repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract version from pom.xml
        id: pom_version
        run: |
          RAW_VERSION=$(grep -m1 "<version>" pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          VERSION=${RAW_VERSION%-SNAPSHOT}
          NEW_TAG="v$VERSION"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Get short SHA with Git
        id: sha_git 
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure Git user
        id: version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Read version from pom.xml file
          
          NEW_TAG="${{ steps.pom_version.outputs.new_tag }}"

          # Prevent duplicate tag
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
             echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Release a new version
        if: steps.version.outputs.tag_exists == 'false'
        run: |
            echo "Tag ${{ steps.pom_version.outputs.new_tag }} will create — release"
            echo "Update PHP proto files - ${{ steps.pom_version.outputs.new_tag }}, entertainer commit: ${{ steps.sha_git.outputs.short_sha }}"

      - name: Tag already exists
        if: steps.pom_version.outputs.tag_exists == 'true'
        run: echo "Tag ${{ steps.version.outputs.new_tag }} already exists — skipping release"
