name: _Stage. Build nginx docker images
on:
  workflow_call:
    inputs:
      deployment-env:
        description: 'Deployment environment'
        required: true
        type: string
      git-ref:
        description: 'Git Reference (Optional. branch/commit hash)'
        required: false
        type: string

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2
  DOCKER_REPOSITORY_NGINX_URI: 055854167589.dkr.ecr.eu-west-2.amazonaws.com/sas-nginx-stage
  DOCKER_REPOSITORY_DOMAIN: 055854167589.dkr.ecr.eu-west-2.amazonaws.com
  GIT_BRANCH: stage

jobs:
  build-nginx:
    name: 'Build nginx for {{ inputs.deployment-env }} environment'
    runs-on: ubuntu-latest
    environment: stage
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ env.GIT_BRANCH }}
        if: github.event.inputs.git-ref == ''

      - name: Checkout Repository (Custom Git Reference)
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.git-ref }}
        if: github.event.inputs.git-ref != ''

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Build image with the nginx
        run: echo "build image nginx"