name: _Stage. Build react docker images
on:
  workflow_call:
    inputs:
      deployment-env:
        description: 'Deployment environment'
        required: true
        type: string
      react-git-ref:
        description: 'React Git Reference (Optional. branch/commit hash)'
        required: false
        type: string
        
env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2
  REACT_ENV_FILE_SECRET_NAME: stage/react_env_file
  DOCKER_REPOSITORY_DOMAIN: 055854167589.dkr.ecr.eu-west-2.amazonaws.com
  DOCKER_REPOSITORY_REACT_URI: 055854167589.dkr.ecr.eu-west-2.amazonaws.com/sas-react-stage
  REACT_GIT_REPOSITORY_URL: "git@github.com:SellerAmp/sas-react.git"
  REACT_GIT_REPOSITORY_BRANCH: stage
  REACT_GIT_DEPLOY_KEY_SECRET_NAME: stage/react_git_deploy_key

jobs:
  build-react:
    name: 'Build react for {{ inputs.deployment-env }} environment'
    runs-on: ubuntu-latest
    environment: stage
    concurrency: stage-${{ github.ref }}
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get secrets from aws secret manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
              REACT_GIT_DEPLOY_KEY, ${{ env.REACT_GIT_DEPLOY_KEY_SECRET_NAME }}
          parse-json-secrets: true

      - name: generate react .env file
        run: echo "Build react"
