name: _Stage. Build react docker images
on:
  workflow_call:
    inputs:
      deployment-env:
        description: 'Deployment environment'
        required: true
        type: string
      react-git-ref:
        description: 'React Git Reference (Optional. branch/commit hash)'
        required: false
        type: string

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2
  REACT_ENV_FILE_SECRET_NAME: stage/react_env_file
  DOCKER_REPOSITORY_DOMAIN: 055854167589.dkr.ecr.eu-west-2.amazonaws.com
  DOCKER_REPOSITORY_REACT_URI: 055854167589.dkr.ecr.eu-west-2.amazonaws.com/sas-react-stage
  REACT_GIT_REPOSITORY_URL: "git@github.com:SellerAmp/sas-react.git"
  REACT_GIT_REPOSITORY_BRANCH: SAP-1488-speed-up-building-react-upon-deployment
  REACT_GIT_DEPLOY_KEY_SECRET_NAME: stage/react_git_deploy_key
  GIT_BRANCH: dev

jobs:
  build-react:
    name: 'Build react for ${{ inputs.deployment-env }} environment'
    runs-on: ubuntu-latest
    environment: stage
    steps:

      - name: Checkout sas repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.GIT_BRANCH }}
          sparse-checkout: |
            aws_secret_manager.sh
            generate_version.sh
          sparse-checkout-cone-mode: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get secrets from aws secret manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
              REACT_GIT_DEPLOY_KEY, ${{ env.REACT_GIT_DEPLOY_KEY_SECRET_NAME }}
          parse-json-secrets: true

      - name: Copy react git deploy key
        run: |
          touch /tmp/react-git-deploy-key.pem
          echo "${{ env.REACT_GIT_DEPLOY_KEY }}" > /tmp/react-git-deploy-key.pem
          chmod 0600 /tmp/react-git-deploy-key.pem
          mkdir -p /tmp/react
        shell: bash

      - name: Clone react repository
        run: |
          if [ "${{ github.event.inputs.react-git-ref }}" == '' ]; then
          GIT_SSH_COMMAND="ssh -i /tmp/react-git-deploy-key.pem -o StrictHostKeyChecking=no" git clone --depth 1 --branch ${{ env.REACT_GIT_REPOSITORY_BRANCH }} ${{ env.REACT_GIT_REPOSITORY_URL }} /tmp/react
          else
          GIT_SSH_COMMAND="ssh -i /tmp/react-git-deploy-key.pem -o StrictHostKeyChecking=no" git clone --depth 1 --branch ${{ github.event.inputs.react-git-ref }} ${{ env.REACT_GIT_REPOSITORY_URL }} /tmp/react
          fi

      - name: Remove react git deploy key
        run: rm /tmp/react-git-deploy-key.pem

      - name: generate react .env file
        run: |
            ./aws_secret_manager.sh  ${{ env.REACT_ENV_FILE_SECRET_NAME }} /tmp/react/.env

      - name: Patch react .env file
        run: |
          NEXT_PUBLIC_VERSION=$(./generate_version.sh | sed 's/\//\\\//g')
          sed -i~ \
            -e 's/{environment}/${{ inputs.deployment-env }}/g' \
            -e "/^NEXT_PUBLIC_VERSION=/s/=.*/=$NEXT_PUBLIC_VERSION/" \
            -e '/^NEXT_PUBLIC_BLUE_GREEN_ENV=/s/=.*/=${{ inputs.deployment-env }}/' \
            /tmp/react/.env
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: /tmp/react
          file: /tmp/react/Dockerfile
          platforms: linux/amd64
          load: true
          outputs: type=docker
          tags: sas-react:latest
          cache-from: type=registry,ref=${{ env.DOCKER_REPOSITORY_REACT_URI }}:build-cache
          cache-to: type=registry,ref=${{ env.DOCKER_REPOSITORY_REACT_URI }}:build-cache,mode=max
