name: _Stage. Build datadog docker images
on:
  workflow_call:
    inputs:
      deployment-env:
        description: 'Deployment environment'
        required: true
        type: string
      git-ref:
        description: 'Git Reference (Optional. branch/commit hash)'
        required: false
        type: string

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2
  DOCKER_REPOSITORY_DATADOG_URI: 055854167589.dkr.ecr.eu-west-2.amazonaws.com/sas-datadog-stage
  DOCKER_REPOSITORY_DOMAIN: 055854167589.dkr.ecr.eu-west-2.amazonaws.com
  DATADOG_API_KEY_SECRET_NAME: stage/datadog_api_key
  GIT_BRANCH: dev

jobs:
  build-datadog:
    name: 'Build datadog for ${{ inputs.deployment-env }} environment'
    runs-on: ubuntu-latest
    environment: stage
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ env.GIT_BRANCH }}
          sparse-checkout: |
            docker/datadog
          sparse-checkout-cone-mode: false
        if: github.event.inputs.git-ref == ''

      - name: Checkout Repository (Custom Git Reference)
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.git-ref }}
          sparse-checkout: |
            docker/datadog
          sparse-checkout-cone-mode: false
        if: github.event.inputs.git-ref != ''

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get secrets from aws secret manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
              ,${{ env.DATADOG_API_KEY_SECRET_NAME }}
          parse-json-secrets: true

      - name: Set Datadog env
        run: echo "APP_ENV=$(awk -F '=' '/APP_ENV=/{print $2}' .env)" >> $GITHUB_ENV

      - name: Build image with the datadog agent
        run: docker build -f ./docker/datadog/Dockerfile -t datadog --build-arg DD_API_KEY=${{ env.DATADOG_API_KEY }} --build-arg DD_ENV=${{ env.APP_ENV }} .

      - name: Authorize to AWS ECR
        run: aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin  ${{ env.DOCKER_REPOSITORY_DOMAIN }}

      - name: Set environment-based Docker tag
        id: docker_tag
        run: echo "tag=${{ inputs.deployment-env }}" >> "$GITHUB_OUTPUT"

      - name: Push image with the datadog agent to Docker registry
        run: |
          docker tag datadog:latest ${{ env.DOCKER_REPOSITORY_DATADOG_URI }}
          docker tag ${{ env.DOCKER_REPOSITORY_DATADOG_URI }}:latest ${{ env.DOCKER_REPOSITORY_DATADOG_URI }}:${{ steps.docker_tag.outputs.tag }}
          docker push ${{ env.DOCKER_REPOSITORY_DATADOG_URI }}:${{ steps.docker_tag.outputs.tag }}