name: Sandbox. Switch Environment (Blue/Green)
run-name: Switch to ${{ inputs.deployment-type }} Environment by ${{ github.actor }} 🚀
on:
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Switch Environment'
        required: true
        type: choice
        options:
          - blue
          - green
      tag:
        description: 'Tag name (e.g. 1.490.0) (Optional)'
        required: false
        type: string
      tag_message:
        description: 'Message for the tag (Optional)'
        required: false
        type: string
    
permissions:
  contents: write   

jobs:
  switch_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Switch Status tag to a new Blue environment
        run: echo "This workflow run for blue"
        if: ( github.event.inputs.deployment-type == 'blue' )

      - name: Switch Load Balancer to Green Target Group
        run: echo "This workflow run for green"
        if: ( github.event.inputs.deployment-type == 'green' )
    
  setup-release-tag:
    if: github.event.inputs.tag != ''
    uses: Eugentk/docker/.github/workflows/set_release_tag.yml@dev
    with:
      tag: github.event.inputs.tag
      tag_message: github.event.inputs.tag_message
    secrets: inherit