name: Sandbox. Switch Environment (Blue/Green)
run-name: Switch to ${{ inputs.deployment-type }} Environment by ${{ github.actor }} 🚀
on:
  workflow_dispatch:
    inputs:
      software-setup:
        description: 'Setup/configure required software on EC2 instances (Optional)'
        default: false
        type: boolean
      deployment-type:
        description: 'Switch Environment'
        required: true
        type: choice
        options:
          - blue
          - green
      tag:
        description: 'Tag name (e.g. 1.490.0) (Optional)'
        required: false
        type: string
      tag_message:
        description: 'Message for the tag (Optional)'
        required: false
        type: string
    
permissions:
  contents: write   

jobs:
  software-setup:
    name: 'Setup/configure required software on EC2 instances'
    if: github.event.inputs.software-setup == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Switch Status tag to a new Blue environment
        run: echo "This workflow run for blue"
        
    
  setup-release-tag:
    if: github.event.inputs.tag != ''
    uses: Eugentk/docker/.github/workflows/set_release_tag.yml@dev
    with:
      tag: github.event.inputs.tag
      tag_message: github.event.inputs.tag_message
    secrets: inherit

  build-blue-env:
    name: 'Build for Blue environment'
    if: |
      always() &&
      github.event.inputs.deployment-type == 'blue'
    runs-on: ubuntu-latest
    steps:
      - name: Switch Status tag to a new Blue environment
        run: echo "This workflow run for blue"