name: Sandbox. Switch Environment (Blue/Green)
run-name: Switch to ${{ inputs.deployment-type }} Environment by ${{ github.actor }} 🚀
on:
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Switch Environment'
        required: true
        type: choice
        options:
          - blue
          - green

jobs:
  switch:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Switch Status tag to a new Blue environment
        run: echo "This workflow run for blue"
        if: ( github.event.inputs.deployment-type == 'blue' )

      - name: Switch Load Balancer to Green Target Group
        run: echo "This workflow run for green"
        if: ( github.event.inputs.deployment-type == 'green' )
    
  call-workflow-passing-data:
    uses: Eugentk/docker/.github/workflows/change_consumers_blue.yml@dev
    with:
      deployment-type: github.event.inputs.deployment-type
    secrets: inherit